<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>disable</Nullable>
    <LangVersion>latest</LangVersion>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>BlackFolder.ico</ApplicationIcon>
    <PublishAot>true</PublishAot>
  </PropertyGroup>

  <ItemGroup>
    <AvaloniaResource Include="Assets\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia.Desktop" Version="11.3.8" />
    <PackageReference Include="Avalonia" Version="11.3.8" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.8" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.3.8" />
    <PackageReference Include="Avalonia.ReactiveUI" Version="11.3.8" />
    <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
    <PackageReference Include="Avalonia.Diagnostics" Version="11.3.8" />
    <PackageReference Include="MuPDFCore" Version="2.0.1" />
    <PackageReference Include="DotNetCampus.AvaloniaInkCanvas" Version="1.0.1" />
  </ItemGroup>
</Project>
